### ISSUE TITLE
Stopping ffmpeg from cluttering stdout/stderr

### ISSUE THREAD

**Issue by thmeier** [thomas-haslwanter/scikit-sound#3]
On macOS, I noticed when creating a `sksound.sounds.Sound()` object that it checks whether ffmpeg and ffplay are available on the system. This happens in the `__init__()` of `class FFMPEG_info()`. I'm not sure why by default one would need such verbose information about how ffmpeg/ffplay were built.
Unfortunately, this unnecessarily clutters stdout/stderr and can be easily fixed by changing

```python3
completed_process = subprocess.run('ffmpeg')
completed_process = subprocess.run('ffplay')
```

to

```python3
completed_process = subprocess.run('ffmpeg', stderr=subprocess.DEVNULL)
completed_process = subprocess.run('ffplay', stderr=subprocess.DEVNULL)
```

I assume that if one is curious about this kind of information, then it should be done by querying ffmpeg/ffplay itself.

Cheers and thanks for this awesome package!

**Comment by thomas-haslwanter** [comment]
Done - Thank you for that feedback: since I don't have a Mac, it is very hard for me to spot such problems!
